<p>事务场景中，抛出异常被catch后，如果需要回滚，一定要手动回滚事务。</p>
<p>Examples:</p>
<pre>

            
Positive example 1：
    /**
     * @author caikang
     * @date 2017/04/07
     */
    @Service
    @Transactional(rollbackFor = Exception.class)
    public class UserServiceImpl implements UserService {
        @Override
        public void save(User user) {
            //some code
            //db operation
        }
    }
        
        
</pre>